# Introduction to Numpy

In [ ]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [6]:
arr #One dimensional arrays

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [9]:
np.array(my_mat) #two dimensional array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.zeros((2,3)) #Inbuilt functions

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [22]:
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [32]:
np.arange(0,10,2) #press shift + tab

array([0, 2, 4, 6, 8])

In [33]:
#Using Linspace 

In [36]:
np.linspace(0,5,100)

array([ 0.        ,  0.05050505,  0.1010101 ,  0.15151515,  0.2020202 ,
        0.25252525,  0.3030303 ,  0.35353535,  0.4040404 ,  0.45454545,
        0.50505051,  0.55555556,  0.60606061,  0.65656566,  0.70707071,
        0.75757576,  0.80808081,  0.85858586,  0.90909091,  0.95959596,
        1.01010101,  1.06060606,  1.11111111,  1.16161616,  1.21212121,
        1.26262626,  1.31313131,  1.36363636,  1.41414141,  1.46464646,
        1.51515152,  1.56565657,  1.61616162,  1.66666667,  1.71717172,
        1.76767677,  1.81818182,  1.86868687,  1.91919192,  1.96969697,
        2.02020202,  2.07070707,  2.12121212,  2.17171717,  2.22222222,
        2.27272727,  2.32323232,  2.37373737,  2.42424242,  2.47474747,
        2.52525253,  2.57575758,  2.62626263,  2.67676768,  2.72727273,
        2.77777778,  2.82828283,  2.87878788,  2.92929293,  2.97979798,
        3.03030303,  3.08080808,  3.13131313,  3.18181818,  3.23232323,
        3.28282828,  3.33333333,  3.38383838,  3.43434343,  3.48

In [40]:
np.eye(4)#Presents a 4*4 identity matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [42]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [3]:
import numpy as np

In [6]:
np.random.rand(10)#creates numbers ranging from 0 to 1

array([ 0.61088294,  0.47292195,  0.98124167,  0.28288825,  0.21859403,
        0.25211369,  0.62255448,  0.24008851,  0.36665204,  0.38071378])

In [9]:
np.random.randn(5)#creates numbers ranging from a standard normal distribution(ie can be both negative and positive)

array([ 0.66551466, -0.12631306,  0.43859163,  0.32463177,  0.7314412 ])

In [13]:
np.random.randint(1,100)#Produces random number within the range provided

95

In [14]:
np.random.randint(1,100,10)#Produces 10 random numbers within the range provided excluding 100


array([29, 57, 89, 55, 24, 62, 57, 19, 47, 59])

In [15]:
arr = np.arange(25)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
ranarr = np.random.randint(0,50,10)

In [18]:
ranarr

array([ 7, 39, 24, 13, 19, 10,  3,  9, 13,  5])

In [19]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
ranarr

array([ 7, 39, 24, 13, 19, 10,  3,  9, 13,  5])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr.shape #Indicates the shape of vector

(25,)

In [34]:
arr = arr.reshape(5,5) #Indicates the shape of vector

In [35]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.shape

(5, 5)

In [124]:
arr.dtype

dtype('int32')

In [125]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [126]:
mat[1:,1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [127]:
mat[2:,1:][1,3]

20

In [132]:
mat[3][4]

20

In [133]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [136]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [137]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Numpy Indexing and Selection

In [8]:
#Has similarities to normal python calling/ indexing

In [3]:
import numpy as np 

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8] #calling the 8th figure

8

In [7]:
arr[1:5] #Calling range from 1 to 4.

array([1, 2, 3, 4])

In [10]:
arr[:6] #print everything up to 5 and is the same as arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:] # Print Everything but start from 5

array([ 5,  6,  7,  8,  9, 10])

# Broadcasting 

In [12]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [13]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
#Now note the changes also occur in our original array!

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
#Data is not copied, it's a view of the original array! This avoids memory problems!

In [23]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# Indexing 2d array/matrices

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. It is recommend to usually use the comma notation for clarity.

In [26]:
import  numpy  as np 

In [27]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[0][0] # Using double bracket notation or row-column to grab 5

5

In [37]:
arr_2d[2][1]# Using row-column to grab 40

40

We can as well use the comma notation, this is recommended.

In [38]:
arr_2d[2,1] #Using comma notation to grab element

40

In [43]:
arr_2d[1,2]#Using comma notation to grab 30

30

Grabing sub matrices

In [75]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

Starting from the row, print everything but end at index 1(ie :2). For the column, print everything but start from index 1(ie 1:)

In [74]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

Starting from the row, print everything but start from index 1(ie 1:). For the column, print everything up to index 1(ie :2)

# CONDITIONAL SELECTION

In [98]:
arr = np.arange(1,11)

In [99]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [100]:
arr>5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [86]:
bool_arr = arr>5

In [87]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [88]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [89]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [90]:
arr[arr<3]

array([1, 2])

In [91]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr_2d = np.arange(50).reshape(5,10)

In [97]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [103]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# NumPy Operations

In [104]:
import numpy as np

In [105]:
arr = np.arange(0,11)

In [106]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
arr + arr #Performing array with array operations

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [108]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [110]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [111]:
arr / arr

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [112]:
#Using Scalars

Say we want operate on each element within the array.  

In [113]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [114]:
arr *100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [115]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [116]:
arr / 100

array([ 0.  ,  0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,
        0.09,  0.1 ])

Universal Operators

In [117]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [118]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [119]:
np.max(arr) #or

10

In [120]:
arr.max()

10

In [121]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [123]:
np.log(arr)

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])

You can go to https://docs.scipy.org/doc/numpy/reference/ufuncs.html for more on operators

In [165]:
np.std(mat)

7.2111025509279782

In [166]:
mat.std()

7.2111025509279782

In [163]:
np.sum(mat)

325

In [167]:
mat.sum()

325

In [168]:
mat.sum(axis=0)#Sums columns 

array([55, 60, 65, 70, 75])

In [162]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [150]:
np.random.randn(5,5)


array([[ 0.45867516, -1.06432151, -2.12866386,  0.84100663, -0.77102298],
       [-0.24023414,  0.00667723, -1.44342436,  0.67042307,  0.32737367],
       [ 0.71961664, -0.44957841,  1.35011795,  1.08573071,  1.52648704],
       [-0.81583412, -1.16323016, -0.6891006 ,  1.53472942,  1.12795695],
       [ 0.3589634 , -1.23242746,  0.34190186, -0.58274852,  0.67233743]])

In [154]:
np.random.randn(25)

array([-0.42519815, -0.31845185,  1.31294364, -0.40051903, -1.81389704,
        0.00208114,  1.85837373,  0.04655123, -0.41008942, -1.06306418,
        0.99698248,  1.34054399, -1.60568126,  0.44832338,  0.07614217,
        0.12021599,  0.45667781,  0.9212876 , -0.65280384,  1.13299962,
       -0.33391354, -0.54377123, -0.00290027, -0.61676446,  1.84737164])

In [153]:
np.random.randn(25).shape # to know that it is 1d

(25,)

In [157]:
np.arange(1,101).reshape(10,10)/100

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [160]:
np.linspace(0.01,1,100).reshape(10,10)

array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])

In [161]:
np.linspace(0,1,20)

array([ 0.        ,  0.05263158,  0.10526316,  0.15789474,  0.21052632,
        0.26315789,  0.31578947,  0.36842105,  0.42105263,  0.47368421,
        0.52631579,  0.57894737,  0.63157895,  0.68421053,  0.73684211,
        0.78947368,  0.84210526,  0.89473684,  0.94736842,  1.        ])